name: CI

on: [push]
  branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: mvn clean verify
      - name: build
        run: ./mvnw compile jib:build
      - name: push
        run:  docker push odfsoft/guess-game:latest
